### ISSUE TITLE
期望补充 demo

### ISSUE THREAD

**Issue by youyeke** [simonguo/markdownLoader#1]
clone 、 install、build、run dev 之后，发现并未渲染出 React 组件。
尝试在 README.md 底部添加如下 markdown: 
```mk
## 示例代码

<!--start-code-->

```js
const instance = <button>Test</button>;
ReactDOM.render(instance);
# ```  这里的 # 号用来防止 GitHub 错误的代码高亮

<!--end-code-->
```
重新build、run dev 之后，也仅仅是渲染了 markdown，并未渲染出 React 组件。

可否补充一下 demo ?

**Comment by simonguo** [comment]
你是不是针对这个库提的问题？
https://github.com/simonguo/react-code-view

**Comment by youyeke** [comment]
👍 是的，我从文章里面点击了错误的 GitHub 连接
